name: docker-image

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - Dockerfile
      - .dockerignore
      - entrypoint.sh
      - .github/workflows/docker-image.yml
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .dockerignore
      - entrypoint.sh
      - .github/workflows/docker-image.yml

permissions: read-all

jobs:
  docker-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build test
        run: docker build . --file Dockerfile
