name: tests

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - tests/**
      - .github/workflows/tests.yml
      - entrypoint.sh
      - Dockerfile
      - .dockerignore
  push:
    branches:
      - master
    paths:
      - tests/**
      - .github/workflows/tests.yml
      - entrypoint.sh
      - Dockerfile
      - .dockerignore

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test 1 - Check done in tests/test2 - tests/test2/normal.md
        uses: ./
        with:
          debug: true
          search_paths: tests/test2

      - name: Test 2 - Check with "exclude" and "search_paths" - tests/test2/normal.md
        uses: ./
        with:
          debug: true
          exclude: |
            CHANGELOG.md
            test1/excluded_file.md
            bad.md
            excluded_dir/
          search_paths: tests/
          quiet: true
